Repository scandipwa/scandipwa, pull requests merged in 2019-05, with the labels that each got.

#141 Styled menu, added images
  src/app/component/Header/Header.style.scss
  src/app/component/Image/Image.component.js
  src/app/component/MenuOverlay/MenuOverlay.component.js
  src/app/component/MenuOverlay/MenuOverlay.connect.js
  src/app/component/MenuOverlay/MenuOverlay.style.scss
  src/app/query/Menu.query.js
  src/app/route/index.js
  src/app/type/Menu.js
  src/app/util/CSS/CSS.js
Labels: PRIORITY: HIGH, PROGRESS: PENDING REVIEW

#140 New radio buttons, checkboxes and select
  src/app/component/CartItem/CartItem.component.js
  src/app/component/CheckoutPreviewAndPaymentsStep/CheckoutPreviewAndPaymentsStep.component.js
  src/app/component/CheckoutShippingStep/CheckoutShippingStep.component.js
  src/app/component/Field/Field.component.js
  src/app/component/Field/Field.style.scss
  src/app/component/Form/Form.component.js
  src/app/component/GroupedProductsItem/GroupedProductsItem.component.js
  src/app/component/MyAccount/MyAccount.component.js
  src/app/component/MyAccountOverlay/MyAccountOverlay.component.js
  src/app/route/MyAccountDetails/MyAccountDetails.component.js
  src/app/route/PasswordChangePage/PasswordChangePage.component.js
Labels: PROGRESS: PENDING REVIEW

#143 MyAccountOverlay styling
  src/app/component/MyAccountOverlay/MyAccountOverlay.component.js
  src/app/component/MyAccountOverlay/MyAccountOverlay.style.scss
  src/app/style/abstract/_button.scss
  src/app/style/base/_input.scss
Labels: PROGRESS: PENDING REVIEW

#145 Will export all reducers for use in theme overrides
  src/app/store/index.js
Labels: PRIORITY: HIGH, enhancement

#144 Add-To-Cart-Frontend
  src/app/query/Cart.query.js
  src/app/store/Cart/Cart.dispatcher.js
Labels: PRIORITY: CRITICAL, PROGRESS: PENDING REVIEW, bug

#160 Added totals support, fixed simple product added attributes field support.
  .graphqlconfig
  .vscode/launch.json
  composer.json
  src/app/component/CartItem/CartItem.component.js
  src/app/component/CartSummary/CartSummary.componet.js
  src/app/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
  src/app/component/CheckoutPreviewAndPaymentsStep/CheckoutPreviewAndPaymentsStep.component.js
  src/app/component/CheckoutShippingStep/CheckoutShippingStep.component.js
  src/app/component/Field/Field.component.js
  src/app/component/Footer/Footer.style.scss
  src/app/component/Form/Form.component.js
  src/app/component/MiniCart/MiniCart.component.js
  src/app/component/MiniCart/MiniCart.container.js
  src/app/component/MyAccount/MyAccount.component.js
  src/app/component/ProductActions/ProductActions.component.js
  src/app/component/ProductCard/ProductCard.component.js
  src/app/component/ProductCard/ProductCard.style.scss
  src/app/component/ProductDescription/ProductDescription.component.js
  src/app/component/ProductDetails/ProductDetails.component.js
  src/app/component/ProductGallery/ProductGallery.component.js
  src/app/component/ProductGallery/ProductGallery.style.scss
  src/app/component/Select/Select.component.js
  src/app/component/Slider/Slider.component.js
  src/app/query/Cart.query.js
  src/app/query/Checkout.query.js
  src/app/query/ProductList.query.js
  src/app/route/CartPage/CartPage.container.js
  src/app/route/CheckoutPage/CheckoutPage.component.js
  src/app/route/MyAccountDetails/MyAccountDetails.component.js
  src/app/route/ProductPage/ProductPage.component.js
  src/app/route/UrlRewrites/UrlRewrites.component.js
  src/app/store/Breadcrumbs/Breadcrumbs.dispatcher.js
  src/app/store/Cart/Cart.action.js
  src/app/store/Cart/Cart.dispatcher.js
  src/app/store/Cart/Cart.reducer.js
  src/app/store/Category/Category.reducer.js
  src/app/store/Product/Product.reducer.js
  src/app/store/RelatedProducts/RelatedProducts.reducer.js
  src/app/util/Query/Field.js
  src/app/util/Query/PrepareDocument.js
  src/config/babel.config.js
Labels: PROGRESS: IN PROGRESS, STATUS: BLOCKED

#163 Added support for currencies
  src/app/component/CartSummary/CartSummary.componet.js
  src/app/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
  src/app/component/MiniCart/MiniCart.component.js
  src/app/component/ProductPrice/ProductPrice.component.js
  src/app/query/Cart.query.js
  src/app/util/Price/Price.js
  src/app/util/Price/index.js
Labels: PRIORITY: HIGH, PROGRESS: PENDING CHANGES
