Repository scandipwa/scandipwa, pull requests merged in 2019-04, with the labels that each got.

#50 Fixed bug when images was still showing placeholder
  src/app/component/CategoryDetails/CategoryDetails.component.js
  src/app/component/CategoryDetails/CategoryDetails.style.scss
  src/app/component/Image/Image.component.js
  src/app/component/Image/Image.style.scss
  src/app/style/base/_root.scss
Labels: PROGRESS: PENDING REVIEW

#44 Custom select category
  src/app/component/ProductSort/ProductSort.component.js
  src/app/component/Select/Select.component.js
  src/app/component/Select/Select.style.scss
  src/app/component/Select/index.js
Labels: PROGRESS: PENDING CHANGES

#77 Added functionality for forgot-password
  src/app/component/MyAccount/MyAccount.component.js
  src/app/component/MyAccount/MyAccount.container.js
  src/app/component/MyAccount/MyAccount.style.scss
  src/app/component/Notification/Notification.style.scss
  src/app/component/NotificationList/NotificationList.style.scss
  src/app/store/MyAccount/MyAccount.action.js
  src/app/store/MyAccount/MyAccount.dispatcher.js
  src/app/store/MyAccount/MyAccount.reducer.js
  src/app/store/MyAccount/index.js
Labels: PRIORITY: NORMAL, PROGRESS: PENDING REVIEW, enhancement

#72 My account create account
  src/app/component/Field/Field.component.js
  src/app/component/Form/Form.component.js
  src/app/component/MyAccount/MyAccount.component.js
  src/app/store/MyAccount/MyAccount.dispatcher.js
Labels: PRIORITY: CRITICAL, PROGRESS: PENDING REVIEW

#69 Fix image loading on new android devices
  src/app/component/Image/Image.component.js
  src/app/component/Image/Image.style.scss
Labels: PRIORITY: HIGH, PROGRESS: READY TO MERGE

#76 Wrong-Breadcrumb-Color
  src/app/component/Breadcrumbs/Breadcrumbs.style.scss
Labels: PRIORITY: LOW, PROGRESS: READY TO MERGE

#89 PDP Input accepts wrong values
  src/app/component/Field/Field.component.js
  src/app/component/ProductActions/ProductActions.component.js
Labels: PRIORITY: HIGH, PROGRESS: READY TO MERGE

#91 My account Change password
  src/app/component/Loader/Loader.component.js
  src/app/component/Loader/Loader.style.scss
  src/app/component/Loader/index.js
  src/app/component/MyAccount/MyAccount.component.js
  src/app/component/MyAccount/MyAccount.style.scss
  src/app/component/Notification/Notification.style.scss
  src/app/query/MyAccount.query.js
  src/app/route/PasswordChangePage/PasswordChangePage.component.js
  src/app/route/PasswordChangePage/PasswordChangePage.container.js
  src/app/route/PasswordChangePage/PasswordChangePage.style.scss
  src/app/route/PasswordChangePage/index.js
  src/app/route/index.js
  src/app/store/MyAccount/MyAccount.dispatcher.js
  src/app/store/MyAccount/MyAccount.reducer.js
Labels: PRIORITY: HIGH, PROGRESS: READY TO MERGE, enhancement

#83 Change links to buttons on My Account
  src/app/component/MyAccount/MyAccount.component.js
  src/app/style/abstract/_variables.scss
Labels: PRIORITY: LOW, PROGRESS: PENDING CHANGES, bug

#94 Added support for extendable routes
  .babelrc
  jsconfig.json
  src/app/route/RouterTemplate/index.js
  src/app/route/index.js
  src/config/babel.config.js
Labels: PRIORITY: HIGH, PROGRESS: PENDING CHANGES

#96 Routes custom items fix
  src/app/route/index.js
Labels: PRIORITY: CRITICAL, PROGRESS: PENDING CHANGES, bug

#75 Select-Sort-Keyboard
  src/app/component/Select/Select.component.js
Labels: PRIORITY: LOW, PROGRESS: READY TO MERGE

#92 Frontend-styles
  src/app/component/Breadcrumbs/Breadcrumbs.style.scss
  src/app/component/CartItem/CartItem.style.scss
  src/app/component/ProductActions/ProductActions.style.scss
  src/app/component/ProductCard/ProductCard.style.scss
  src/app/component/ProductDetails/ProductDetails.style.scss
  src/app/component/RelatedProducts/RelatedProducts.style.scss
  src/app/route/CartPage/CartPage.style.scss
Labels: PRIORITY: NORMAL, PROGRESS: READY TO MERGE, enhancement

#99 #97 Fix image path
  src/app/component/CartItem/CartItem.component.js
  src/app/component/GroupedProductsItem/GroupedProductsItem.component.js
  src/app/component/ProductCard/ProductCard.component.js
  src/app/component/ProductGallery/ProductGallery.component.js
  src/app/component/Slider/Slider.component.js
  src/app/query/ProductList/ProductList.js
Labels: PRIORITY: HIGH, PROGRESS: PENDING REVIEW, bug

#90 Fix grouped product persisted quantity
  src/app/component/GroupedProductsItem/GroupedProductsItem.component.js
  src/app/component/GroupedProductsList/GroupedProductsList.component.js
  src/app/component/GroupedProductsList/GroupedProductsList.container.js
  src/app/component/GroupedProductsList/index.js
  src/app/store/Product/Product.reducer.js
Labels: PRIORITY: NORMAL, PROGRESS: READY TO MERGE, bug

#104 Fix for slider's animations and irrelevant focus on slide change
  src/app/component/Slider/Slider.component.js
Labels: PRIORITY: NORMAL, PROGRESS: PENDING REVIEW

#116 Allow absolute paths only in Image and slider routes fix
  src/app/component/Image/Image.component.js
  src/app/component/ProductGallery/ProductGallery.component.js
  src/app/component/Slider/Slider.component.js
  src/app/store/CmsBlocksAndSlider/CmsBlocksAndSlider.reducer.js
Labels: PROGRESS: READY TO MERGE

#98 My account address
  src/app/component/MyAccount/MyAccount.component.js
  src/app/component/MyAccount/MyAccount.style.scss
  src/app/query/MyAccount.query.js
  src/app/route/MyAccountDetails/MyAccountDetails.component.js
  src/app/route/MyAccountDetails/MyAccountDetails.container.js
  src/app/route/MyAccountDetails/MyAccountDetails.style.scss
  src/app/route/MyAccountDetails/index.js
  src/app/route/index.js
  src/app/store/MyAccount/MyAccount.dispatcher.js
  src/app/util/Query/PrepareDocument.js
  src/app/util/Query/index.js
Labels: PRIORITY: CRITICAL, PROGRESS: PENDING REVIEW

#121 Fix for first loading of my account
  src/app/route/MyAccountDetails/MyAccountDetails.component.js
Labels: PRIORITY: CRITICAL, PROGRESS: PENDING REVIEW, bug

#123 Added MAGENTO_VERSION variable to the core config
  src/config/webpack.core.config.js
Labels: PRIORITY: CRITICAL, enhancement

#130 My-Account-Passwords-Match
  src/app/route/MyAccountDetails/MyAccountDetails.component.js
  src/app/store/MyAccount/MyAccount.dispatcher.js
Labels: PRIORITY: HIGH, PROGRESS: READY TO MERGE, bug

#125 Native select on mobile
  src/app/component/Select/Select.component.js
  src/app/component/Select/Select.style.scss
Labels: PRIORITY: LOW, PROGRESS: PENDING REVIEW, enhancement

#120 Fix sync between qty of mini-cart and cart
  src/app/component/Field/Field.component.js
Labels: PRIORITY: NORMAL, PROGRESS: READY TO MERGE, bug

#136 Checkout country select
  src/app/component/CheckoutShippingStep/CheckoutShippingStep.component.js
  src/app/component/CheckoutShippingStep/CheckoutShippingStep.container.js
  src/app/component/Field/Field.component.js
  src/app/component/Field/index.js
  src/app/component/Form/Form.component.js
  src/app/component/MyAccount/MyAccount.style.scss
  src/app/component/ProductSort/ProductSort.component.js
  src/app/component/Select/Select.component.js
  src/app/component/Select/Select.style.scss
  src/app/query/HeaderAndFooter.query.js
  src/app/route/CategoryPage/CategoryPage.component.js
  src/app/route/CheckoutPage/CheckoutPage.style.scss
  src/app/route/MyAccountDetails/MyAccountDetails.component.js
  src/app/route/MyAccountDetails/MyAccountDetails.container.js
  src/app/route/MyAccountDetails/MyAccountDetails.style.scss
  src/app/route/RouterTemplate/index.js
  src/app/route/index.js
  src/app/store/HeaderAndFooter/HeaderAndFooter.action.js
  src/app/store/HeaderAndFooter/HeaderAndFooter.dispatcher.js
  src/app/store/HeaderAndFooter/HeaderAndFooter.reducer.js
  src/app/store/HeaderAndFooter/index.js
  src/config/webpack.core.config.js
  src/config/webpack.production.config.js
Labels: PROGRESS: PENDING REVIEW, enhancement
