Repository scandipwa/scandipwa, pull requests merged in 2019-12, with the labels that each got.

#422 Stripe integration
  composer.json
  package-lock.json
  package.json
  src/app/component/CheckoutBilling/CheckoutBilling.component.js
  src/app/component/CheckoutBilling/CheckoutBilling.container.js
  src/app/component/CheckoutPayments/CheckoutPayments.component.js
  src/app/component/CheckoutPayments/CheckoutPayments.container.js
  src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.component.js
  src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.container.js
  src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.style.scss
  src/app/component/InjectedStripeCheckoutForm/index.js
  src/app/component/Stripe/Stripe.component.js
  src/app/component/Stripe/Stripe.container.js
  src/app/component/Stripe/Stripe.style.scss
  src/app/component/Stripe/index.js
  src/app/route/Checkout/Checkout.container.js
  src/public/index.development.html
  src/public/index.production.html
Labels: PRIORITY: HIGH, STATUS: ON HOLD

#339 Pass guest quote id along with a login request
  src/app/query/MyAccount.query.js
Labels: PRIORITY: HIGH, STATUS: BLOCKED

#373 Inventory allowed min / max qty check
  composer.json
  src/app/component/CartItem/CartItem.component.js
  src/app/component/CartItem/CartItem.container.js
  src/app/component/ProductActions/ProductActions.component.js
  src/app/component/ProductActions/ProductActions.container.js
  src/app/query/ProductList.query.js
  src/app/store/Cart/Cart.dispatcher.js
Labels: PRIORITY: NORMAL, STATUS: BLOCKED

#386 [SWPWA-273] Styling for tables, iframes, fix for cms translations
  src/app/component/Html/Html.component.js
  src/app/query/CmsPage.query.js
  src/app/style/base/_reset.scss
  src/app/style/base/_table.scss
Labels: PROGRESS: PENDING CHANGES
