Repository scandipwa/scandipwa, pull requests merged in 2019-08, with the labels that each got.

#174 Swipeable slider. Clickable sides, crumbs - change big Image.
  src/app/component/Draggable/Draggable.component.js
  src/app/component/ProductGallery/ProductGallery.component.js
  src/app/component/Slider/Slider.component.js
Labels: PRIORITY: NORMAL, PROGRESS: PENDING CHANGES

#237 Fixed discount bug
  src/app/component/CartSummary/CartSummary.componet.js
Labels: PRIORITY: HIGH, PROGRESS: PENDING CHANGES, bug

#278 Rewrtied components export declaration
  src/app/component/AddToCart/AddToCart.component.js
  src/app/component/Breadcrumbs/Breadcrumbs.component.js
  src/app/component/CartItem/CartItem.component.js
  src/app/component/CartOverlay/CartOverlay.component.js
  src/app/component/CategoryDetails/CategoryDetails.component.js
  src/app/component/CategoryFilterOverlay/CategoryFilterOverlay.component.js
  src/app/component/CategoryPagination/CategoryPagination.component.js
  src/app/component/CategoryProductList/CategoryProductList.component.js
  src/app/component/CategorySearch/CategorySearch.component.js
  src/app/component/CategorySort/CategorySort.component.js
  src/app/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
  src/app/component/CheckoutPaymentMethods/CheckoutPaymentMethods.component.js
  src/app/component/CheckoutPreviewAndPaymentsStep/CheckoutPreviewAndPaymentsStep.component.js
  src/app/component/CheckoutShippingMethods/CheckoutShippingMethods.component.js
  src/app/component/CheckoutShippingStep/CheckoutShippingStep.component.js
  src/app/component/ClickOutside/ClickOutside.component.js
  src/app/component/ContentWrapper/ContentWrapper.component.js
  src/app/component/Draggable/Draggable.component.js
  src/app/component/ExpandableContent/ExpandableContent.component.js
  src/app/component/Field/Field.component.js
  src/app/component/Footer/Footer.component.js
  src/app/component/Form/Form.component.js
  src/app/component/GroupedProductsItem/GroupedProductsItem.component.js
  src/app/component/GroupedProductsList/GroupedProductsList.component.js
  src/app/component/Header/Header.component.js
  src/app/component/HomeSlider/HomeSlider.component.js
  src/app/component/Html/Html.component.js
  src/app/component/Image/Image.component.js
  src/app/component/Link/Link.component.js
  src/app/component/Loader/Loader.component.js
  src/app/component/MenuOverlay/MenuOverlay.component.js
  src/app/component/Meta/Meta.component.js
  src/app/component/MyAccountSidebar/MyAccountSidebar.component.js
  src/app/component/Notification/Notification.component.js
  src/app/component/NotificationList/NotificationList.component.js
  src/app/component/Overlay/Overlay.component.js
  src/app/component/ProductActions/ProductActions.component.js
  src/app/component/ProductAttributeValue/ProductAttributeValue.component.js
  src/app/component/ProductCard/ProductCard.component.js
  src/app/component/ProductConfigurableAttributes/ProductConfigurableAttributes.component.js
  src/app/component/ProductGallery/ProductGallery.component.js
  src/app/component/ProductInformation/ProductInformation.component.js
  src/app/component/ProductPrice/ProductPrice.component.js
  src/app/component/ProductReviewForm/ProductReviewForm.component.js
  src/app/component/ProductReviewList/ProductReviewList.component.js
  src/app/component/ProductReviewRating/ProductReviewRating.component.js
  src/app/component/ProductWishlistButton/ProductWishlistButton.component.js
  src/app/component/RangeSelector/RangeSelector.component.js
  src/app/component/RelatedProducts/RelatedProducts.component.js
  src/app/component/SearchOverlay/SearchOverlay.component.js
  src/app/component/Slider/Slider.component.js
  src/app/component/TextPlaceholder/TextPlaceholder.component.js
Labels: PRIORITY: HIGH, PROGRESS: PENDING CHANGES
