Repository scandipwa/scandipwa, pull requests merged in 2019-06, with the labels that each got.

#159 Wishlist Page in My Account
  src/app/component/AddToCart/AddToCart.component.js
  src/app/component/AddToCart/AddToCart.container.js
  src/app/component/MyAccountSidebar/MyAccountSidebar.component.js
  src/app/component/MyAccountSidebar/MyAccountSidebar.style.scss
  src/app/component/MyAccountSidebar/index.js
  src/app/component/ProductCard/ProductCard.component.js
  src/app/component/ProductCard/ProductCard.container.js
  src/app/component/ProductWishlistButton/ProductWishlistButton.component.js
  src/app/route/MyAccountWishlist/MyAccountWishlist.component.js
  src/app/route/MyAccountWishlist/MyAccountWishlist.container.js
  src/app/route/MyAccountWishlist/MyAccountWishlist.style.scss
  src/app/route/MyAccountWishlist/index.js
  src/app/route/index.js
  src/app/store/Wishlist/Wishlist.action.js
  src/app/store/Wishlist/Wishlist.dispatcher.js
  src/app/store/Wishlist/Wishlist.reducer.js
  src/app/store/Wishlist/index.js
Labels: PRIORITY: HIGH, PROGRESS: REQUIRES TEST

#176 Adding additional validations
  src/app/component/CheckoutPreviewAndPaymentsStep/CheckoutPreviewAndPaymentsStep.component.js
  src/app/component/CheckoutShippingStep/CheckoutShippingStep.component.js
  src/app/component/Field/Field.component.js
  src/app/component/Field/Field.style.scss
  src/app/component/Form/Form.component.js
  src/app/query/CheckEmail.query.js
  src/app/query/index.js
Labels: PROGRESS: REQUIRES TEST

#171 Will not let users to cart and checkout with empty cart Issue #169
  src/app/component/CartSummary/CartSummary.componet.js
  src/app/component/CartSummary/CartSummary.style.scss
  src/app/component/MiniCart/MiniCart.component.js
  src/app/component/MiniCart/MiniCart.style.scss
Labels: PRIORITY: NORMAL, PROGRESS: PENDING CHANGES

#168 String literals support for future translation implementation
  .eslintrc
  src/app/component/AddToCart/AddToCart.component.js
  src/app/component/Breadcrumbs/Breadcrumbs.component.js
  src/app/component/CartItem/CartItem.component.js
  src/app/component/CartSummary/CartSummary.componet.js
  src/app/component/CategoriesList/CategoriesList.component.js
  src/app/component/CategoryShoppingOptions/CategoryShoppingOptions.component.js
  src/app/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
  src/app/component/CheckoutPaymentMethods/CheckoutPaymentMethods.component.js
  src/app/component/CheckoutPreviewAndPaymentsStep/CheckoutPreviewAndPaymentsStep.component.js
  src/app/component/CheckoutShippingMethods/CheckoutShippingMethods.component.js
  src/app/component/CheckoutShippingStep/CheckoutShippingStep.component.js
  src/app/component/DiscountCoupons/DiscountCoupons.component.js
  src/app/component/Footer/Footer.component.js
  src/app/component/Form/Form.config.js
  src/app/component/Header/Header.component.js
  src/app/component/MiniCart/MiniCart.component.js
  src/app/component/MyAccount/MyAccount.component.js
  src/app/component/MyAccountSidebar/MyAccountSidebar.component.js
  src/app/component/ProductCard/ProductCard.component.js
  src/app/component/ProductDescription/ProductDescription.component.js
  src/app/component/ProductDetails/ProductDetails.component.js
  src/app/component/ProductPrice/ProductPrice.component.js
  src/app/component/ProductSort/ProductSort.component.js
  src/app/component/ProductWishlistButton/ProductWishlistButton.component.js
  src/app/component/RelatedProducts/RelatedProducts.component.js
  src/app/component/SearchBar/SearchBar.component.js
  src/app/route/CartPage/CartPage.component.js
  src/app/route/CategoryPage/CategoryPage.component.js
  src/app/route/CheckoutPage/CheckoutPage.component.js
  src/app/route/HomePage/HomePage.component.js
  src/app/route/MyAccountDetails/MyAccountDetails.component.js
  src/app/route/MyAccountWishlist/MyAccountWishlist.component.js
  src/app/route/NoMatch/NoMatch.component.js
  src/app/route/PasswordChangePage/PasswordChangePage.component.js
  src/app/route/ProductPage/ProductPage.component.js
  src/config/TranslationFunction/index.js
  src/config/webpack.core.config.js
  src/config/webpack.development.config.js
  src/config/webpack.production.config.js
  src/public/index.development.html
  src/public/index.production.html
  src/sw/index.js
  src/sw/util/Workbox.js
Labels: PRIORITY: HIGH, PROGRESS: REQUIRES TEST

#183 Added product and category canonical URL to head
  composer.json
  src/app/component/Meta/Meta.component.js
  src/app/query/Category.query.js
Labels: PRIORITY: HIGH, PROGRESS: IN PROGRESS
