Repository scandipwa/scandipwa, pull requests merged in 2019-07, with the labels that each got.

#208 Implemented review feature
  composer.json
  package-lock.json
  package.json
  src/app/component/CategoryProductList/CategoryProductList.style.scss
  src/app/component/Field/Field.component.js
  src/app/component/Field/Field.style.scss
  src/app/component/Form/Form.component.js
  src/app/component/ProductCard/ProductCard.component.js
  src/app/component/ProductCard/ProductCard.style.scss
  src/app/component/ProductDescription/ProductDescription.style.scss
  src/app/component/ProductDetails/ProductDetails.component.js
  src/app/component/ProductDetails/ProductDetails.style.scss
  src/app/component/ProductReviewForm/ProductReviewForm.component.js
  src/app/component/ProductReviewForm/ProductReviewForm.container.js
  src/app/component/ProductReviewForm/ProductReviewForm.style.scss
  src/app/component/ProductReviewForm/index.js
  src/app/component/ProductReviewList/ProductReviewList.component.js
  src/app/component/ProductReviewList/ProductReviewList.style.scss
  src/app/component/ProductReviewList/index.js
  src/app/component/ProductReviewRating/ProductReviewRating.component.js
  src/app/component/ProductReviewRating/ProductReviewRating.style.scss
  src/app/component/ProductReviewRating/index.js
  src/app/component/RelatedProducts/RelatedProducts.component.js
  src/app/component/RelatedProducts/RelatedProducts.style.scss
  src/app/query/ProductList.query.js
  src/app/query/Review.query.js
  src/app/query/index.js
  src/app/route/ProductPage/ProductPage.component.js
  src/app/route/ProductPage/ProductPage.style.scss
  src/app/route/index.js
  src/app/store/Config/Config.action.js
  src/app/store/Config/Config.dispatcher.js
  src/app/store/Config/Config.reducer.js
  src/app/store/Config/index.js
  src/app/store/HeaderAndFooter/HeaderAndFooter.action.js
  src/app/store/HeaderAndFooter/HeaderAndFooter.dispatcher.js
  src/app/store/HeaderAndFooter/HeaderAndFooter.reducer.js
  src/app/store/HeaderAndFooter/index.js
  src/app/store/Review/Review.dispatcher.js
  src/app/store/Review/index.js
  src/app/store/index.js
  src/app/style/base/_input.scss
  src/app/type/ProductList.js
  src/app/type/Rating.js
  src/app/util/Link/Link.js
  src/app/util/Link/index.js
  src/app/util/Review/Review.js
  src/app/util/Review/index.js
Labels: PRIORITY: CRITICAL

#180 Adding dynamic limits for price ranges for category price filter
  src/app/query/ProductList.query.js
  src/app/route/CategoryPage/CategoryPage.component.js
  src/app/route/CategoryPage/CategoryPage.container.js
  src/app/store/Category/Category.action.js
  src/app/store/Category/Category.dispatcher.js
  src/app/store/Category/Category.reducer.js
Labels: PRIORITY: NORMAL, STATUS: ON HOLD

#236 Seo scroll
  src/app/component/CategoryPagination/CategoryPagination.component.js
  src/app/component/CategoryPagination/CategoryPagination.style.scss
  src/app/component/CategoryPagination/index.js
  src/app/component/CategoryProductList/CategoryProductList.component.js
  src/app/component/CategoryProductList/CategoryProductList.style.scss
  src/app/component/CategoryProductListPlaceholder/CategoryProductListPlaceholder.component.js
  src/app/component/CategoryProductListPlaceholder/CategoryProductListPlaceholder.style.scss
  src/app/component/CategoryProductListPlaceholder/index.js
  src/app/query/ProductList.query.js
  src/app/route/CategoryPage/CategoryPage.component.js
  src/app/route/CategoryPage/CategoryPage.container.js
  src/app/route/SearchPage/SearchPage.component.js
  src/app/route/SearchPage/SearchPage.container.js
  src/app/store/Category/Category.action.js
  src/app/store/Category/Category.dispatcher.js
  src/app/store/Category/Category.reducer.js
  src/app/store/Category/index.js
  src/app/store/ProductList/ProductList.action.js
  src/app/store/ProductList/ProductList.dispatcher.js
  src/app/store/ProductList/ProductList.reducer.js
  src/app/store/ProductList/index.js
  src/app/store/ProductListInfo/ProductListInfo.action.js
  src/app/store/ProductListInfo/ProductListInfo.dispatcher.js
  src/app/store/ProductListInfo/ProductListInfo.reducer.js
  src/app/store/ProductListInfo/index.js
  src/app/store/index.js
  src/app/type/ProductList.js
  src/app/util/Url/Url.js
  src/app/util/Url/index.js
Labels: PRIORITY: CRITICAL, PROGRESS: PENDING CHANGES, enhancement
