Repository scandipwa/scandipwa, pull requests merged in 2019-09, with the labels that each got.

#289 Lint no bind
  .eslintrc
  src/app/component/CategoryPagination/CategoryPagination.component.js
  src/app/component/CategoryPagination/CategoryPagination.container.js
  src/app/component/CategoryPagination/CategoryPagination.style.scss
  src/app/component/CategoryPaginationLink/CategoryPaginationLink.component.js
  src/app/component/CategoryPaginationLink/CategoryPaginationLink.style.scss
  src/app/component/CategoryPaginationLink/index.js
  src/app/component/CategoryProductList/CategoryProductList.container.js
  src/app/component/CategorySearch/CategorySearch.component.js
  src/app/component/CategorySort/CategorySort.component.js
  src/app/component/CheckoutPaymentMethod/CheckoutPaymentMethod.component.js
  src/app/component/CheckoutPaymentMethod/index.js
  src/app/component/CheckoutPaymentMethods/CheckoutPaymentMethods.component.js
  src/app/component/CheckoutPreviewAndPaymentsStep/CheckoutPreviewAndPaymentsStep.component.js
  src/app/component/CheckoutShippingMethod/CheckoutShippingMethod.component.js
  src/app/component/CheckoutShippingMethod/index.js
  src/app/component/CheckoutShippingMethods/CheckoutShippingMethods.component.js
  src/app/component/CheckoutShippingStep/CheckoutShippingStep.component.js
  src/app/component/CheckoutShippingStep/CheckoutShippingStep.container.js
  src/app/component/ClickOutside/ClickOutside.component.js
  src/app/component/Draggable/Draggable.component.js
  src/app/component/ExpandableContent/ExpandableContent.component.js
  src/app/component/Field/Field.component.js
  src/app/component/Form/Form.component.js
  src/app/component/GroupedProductsItem/GroupedProductsItem.component.js
  src/app/component/MenuOverlay/MenuOverlay.component.js
  src/app/component/MyAccountOverlay/MyAccountOverlay.component.js
  src/app/component/Notification/Notification.component.js
  src/app/component/ProductActions/ProductActions.component.js
  src/app/component/ProductAttributeValue/ProductAttributeValue.component.js
  src/app/component/ProductConfigurableAttributes/ProductConfigurableAttributes.component.js
  src/app/component/ProductGallery/ProductGallery.component.js
  src/app/component/ProductGalleryImage/ProductGalleryImage.component.js
  src/app/component/ProductGalleryImage/ProductGalleryImage.style.scss
  src/app/component/ProductGalleryImage/index.js
  src/app/component/ProductReviewForm/ProductReviewForm.component.js
  src/app/component/ProductWishlistButton/ProductWishlistButton.component.js
  src/app/component/RangeSelector/RangeSelector.component.js
  src/app/component/ReviewStar/ReviewStar.component.js
  src/app/component/ReviewStar/index.js
  src/app/component/SearchOverlay/SearchOverlay.component.js
  src/app/route/CheckoutPage/CheckoutPage.component.js
  src/app/route/CheckoutPage/CheckoutPage.container.js
  src/app/route/PasswordChangePage/PasswordChangePage.component.js
Labels: PRIORITY: NORMAL, PROGRESS: IN PROGRESS

#292 Added support for coupons
  composer.json
  src/app/component/CartCoupon/CartCoupon.component.js
  src/app/component/CartCoupon/CartCoupon.container.js
  src/app/component/CartCoupon/CartCoupon.style.scss
  src/app/component/CartCoupon/index.js
  src/app/component/CartOverlay/CartOverlay.component.js
  src/app/component/CartOverlay/CartOverlay.style.scss
  src/app/query/Cart.query.js
  src/app/route/CartPage/CartPage.component.js
  src/app/route/CartPage/CartPage.container.js
  src/app/route/CartPage/CartPage.style.scss
  src/app/store/Cart/Cart.action.js
  src/app/store/Cart/Cart.dispatcher.js
Labels: PRIORITY: CRITICAL, STATUS: BLOCKED

#291 Fixed 'Subscribe to newsletter'
  composer.json
  src/app/component/Field/Field.component.js
  src/app/component/MyAccountOverlay/MyAccountOverlay.component.js
Labels: PRIORITY: HIGH, PROGRESS: PENDING CHANGES

#312 Ported 'Cart improvements' changes from V1
  src/app/component/CartItem/CartItem.component.js
  src/app/component/CartItem/CartItem.container.js
  src/app/component/CartItemPrice/CartItemPrice.component.js
  src/app/component/CartItemPrice/index.js
  src/app/component/CartOverlay/CartOverlay.component.js
  src/app/component/CartOverlay/CartOverlay.container.js
  src/app/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
  src/app/component/ProductCard/ProductCard.container.js
  src/app/component/ProductPrice/ProductPrice.component.js
  src/app/component/ProductPrice/ProductPrice.container.js
  src/app/query/Cart.query.js
  src/app/route/CartPage/CartPage.component.js
  src/app/route/CartPage/CartPage.container.js
  src/app/route/CheckoutPage/CheckoutPage.component.js
  src/app/route/ProductPage/ProductPage.container.js
  src/app/store/Cart/Cart.action.js
  src/app/store/Cart/Cart.dispatcher.js
  src/app/store/Cart/Cart.reducer.js
  src/app/type/MiniCart.js
  src/app/util/Price/Price.js
  src/app/util/Url/Url.js
Labels: PRIORITY: CRITICAL
