Repository scandipwa/scandipwa, pull requests merged in 2021-01, with the labels that each got.

#2033 Compare Page Sticky Labels
  packages/scandipwa/src/component/ProductCompare/ProductCompare.style.scss
  packages/scandipwa/src/component/ProductCompareAttributeRow/ProductCompareAttributeRow.style.scss
Labels: Status: QA Passed, Status: Waiting Review

#2050 SWPWA-1724 - Mobile: Button 'Ok' changes to 'Edit' in edit mode if user removed product from Wishlist
  packages/scandipwa/src/route/MyAccount/MyAccount.container.js
Labels: Status: QA Passed

#2049 Mobile: Page leads to Ooops page if user deleted product with swipe delete from the Wishlist and then deleted product in edit mode
  packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
Labels: Status: QA Passed

#2048 refactored unsupported flatMap() since unnecessary
  packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
  packages/scandipwa/src/route/CartPage/CartPage.component.js
Labels: Status: QA Passed

#2034 #2016 - Fixed loader when deleting items from wishlist
  packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.component.js
  packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.container.js
  packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js
Labels: Status: QA Passed, Status: Waiting Review

#2032 Bundled product price
  packages/scandipwa/src/component/ProductActions/ProductActions.container.js
  packages/scandipwa/src/component/ProductBundleItems/ProductBundleItems.container.js
  packages/scandipwa/src/route/ProductPage/ProductPage.component.js
  packages/scandipwa/src/route/ProductPage/ProductPage.container.js
Labels: Status: QA Passed, Status: Waiting Review

#2026 #2024 - Changed the Newsletter Subscription's success notification message
  packages/scandipwa/src/store/NewsletterSubscription/NewsletterSubscription.dispatcher.js
Labels: Status: QA Passed

#2027 2014-fixed-x-button-position
  packages/scandipwa/src/component/CartItem/CartItem.style.scss
Labels: Status: QA Passed

#2054 Changed items stream propery
  packages/scandipwa/src/route/CartPage/CartPage.container.js
Labels: Status: QA Passed

#2053 Changed FieldSelect Options overflow setting
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Status: QA Passed

#2084 Comparable Attribute Values
  packages/scandipwa/src/component/ProductCompare/ProductCompare.config.js
  packages/scandipwa/src/component/ProductCompare/ProductCompare.container.js
Labels: Status: QA Passed

#2082 Reopened issue flex items width improvement
  packages/scandipwa/src/component/CartItem/CartItem.style.scss
Labels: Status: QA Passed

#2056 Changed CartPage container properties
  packages/scandipwa/src/route/CartPage/CartPage.container.js
Labels: Status: QA Passed

#2090 Improved applied_taxes rates mapping
  packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
  packages/scandipwa/src/route/CartPage/CartPage.component.js
Labels: Status: QA Passed

#2047 2013 wrong password validation error
  .vscode/launch.json
  packages/scandipwa/src/component/Field/Field.container.js
  packages/scandipwa/src/component/Form/Form.component.js
Labels: Status: QA Passed

#2072 Add To Cart Button In Compare Page
  packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.style.scss
  packages/scandipwa/src/component/ShareWishlistPopup/ShareWishlistPopup.container.js
Labels: Status: QA Passed

#2103 #1559 - 'Not found' page isn't rendered if a disabled CMS page is loaded
  packages/scandipwa/src/route/CmsPage/CmsPage.component.js
  packages/scandipwa/src/route/CmsPage/CmsPage.container.js
  packages/scandipwa/src/route/NoMatch/NoMatch.container.js
  packages/scandipwa/src/route/UrlRewrites/UrlRewrites.component.js
  packages/scandipwa/src/route/UrlRewrites/UrlRewrites.container.js
Labels: Status: QA Passed

#2106 2058 product page scroll down issue
  packages/scandipwa/src/component/Router/Router.container.js
Labels: Status: Failed QA

#2089 Zero Tax Display
  packages/scandipwa/src/component/CartOverlay/CartOverlay.container.js
Labels: Status: QA Passed

#2087 Implemented support for anchor category setting
  packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.component.js
  packages/scandipwa/src/query/Category.query.js
  packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
Labels: Status: QA Passed
