Repository scandipwa/scandipwa, pull requests merged in 2021-08, with the labels that each got.

#3045 issue - 3043 - Set default values for getting Customizable prices
  packages/scandipwa/src/component/ProductActions/ProductActions.container.js
Labels: Status: QA Passed

#3085 #3082 Ooops on select when using keyboard
  packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js
  packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js
Labels: Status: QA Passed

#3060 Removal of non-used imports
  packages/scandipwa/package.json
  packages/scandipwa/src/component/AddToCart/AddToCart.component.js
  packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js
  packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.component.js
  packages/scandipwa/src/component/ExpandableContent/ExpandableContent.component.js
  packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.component.js
  packages/scandipwa/src/component/MyAccountTabList/MyAccountTabList.component.js
  packages/scandipwa/src/component/Overlay/Overlay.component.js
  packages/scandipwa/src/component/PopupSuspense/PopupSuspense.component.js
  packages/scandipwa/src/component/ProductCard/ProductCard.component.js
  packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js
  packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js
  packages/scandipwa/src/component/ProductDownloadableSamples/ProductDownloadableSamples.component.js
  packages/scandipwa/src/component/SearchOverlay/SearchOverlay.component.js
  packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js
  yarn.lock
Labels: Status: QA Passed

#3086 issue-3070 - Pass onClick function for edit icon
  packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js
Labels: Status: QA Passed

#3076 Bugfix/fix missing welcome message
  packages/scandipwa/src/component/Header/Header.component.js
  packages/scandipwa/src/component/Header/Header.style.scss
Labels: Status: QA Passed

#3052 #2868 - wrong slider direction
  packages/scandipwa/src/component/Slider/Slider.component.js
  packages/scandipwa/src/component/SliderWidget/SliderWidget.component.js
  packages/scandipwa/src/component/SliderWidget/SliderWidget.config.js
Labels: Status: QA Passed

#3018 2944/standalone mode detection
  packages/scandipwa/public/icon_ios_640x640.png
  packages/scandipwa/public/index.html
  packages/scandipwa/public/manifest.json
  packages/scandipwa/src/style/abstract/_icons.scss
  packages/scandipwa/src/util/Mobile/isMobile.js
Labels: Status: QA Passed

#2942 #2863 Correct coupon field colors.
  packages/scandipwa/src/component/CartCoupon/CartCoupon.component.js
  packages/scandipwa/src/component/Field/Field.config.js
  packages/scandipwa/src/component/Field/Field.container.js
Labels: Status: QA Passed

#3071 #2547 - fix image on CMS page styled different from Magento admin styling
  packages/scandipwa/src/component/Footer/Footer.config.js
  packages/scandipwa/src/component/Html/Html.component.js
  packages/scandipwa/src/component/Image/Image.component.js
  packages/scandipwa/src/component/Image/Image.config.js
  packages/scandipwa/src/component/Logo/Logo.component.js
  packages/scandipwa/src/route/StyleGuidePage/StyleGuidePage.config.js
  packages/scandipwa/src/style/icons/logos/facebook.svg
  packages/scandipwa/src/style/icons/logos/linkedIn.svg
  packages/scandipwa/src/style/icons/logos/mainLogo.svg
  packages/scandipwa/src/style/icons/logos/twitter.svg
Labels: Status: QA Passed

#2490 Will retain link parameters when popup is opened
  packages/scandipwa/src/component/Popup/Popup.component.js
Labels: Status: QA Passed

#3091 #3079 - missing hover effect
  packages/scandipwa/src/component/MyAccountMyWishlist/MyAccountMyWishlist.style.scss
  packages/scandipwa/src/style/abstract/_button.scss
Labels: Status: QA Passed

#3059 Navigation abstract performance optimizations
  packages/scandipwa/src/component/Header/Header.component.js
  packages/scandipwa/src/component/NavigationAbstract/NavigationAbstract.component.js
  packages/scandipwa/src/component/NavigationTabs/NavigationTabs.component.js
Labels: Status: QA Passed

#3160 #2468 Search page replace none with best match sort
  packages/scandipwa/src/component/CategorySort/CategorySort.container.js
  packages/scandipwa/src/route/SearchPage/SearchPage.config.js
  packages/scandipwa/src/route/SearchPage/SearchPage.container.js
Labels: Status: QA Passed

#3139 3126/improve lighthouse scores
  packages/m2-theme/public/index.php
  packages/scandipwa/public/index.html
  packages/scandipwa/public/manifest.json
  packages/scandipwa/public/maskable_icon_x192.png
  packages/scandipwa/src/component/CookiePopup/CookiePopup.component.js
  packages/scandipwa/src/component/Field/Field.container.js
  packages/scandipwa/src/component/FieldForm/FieldForm.component.js
  packages/scandipwa/src/component/FieldInput/FieldInput.component.js
  packages/scandipwa/src/component/FieldInput/FieldInput.container.js
  packages/scandipwa/src/component/Header/Header.component.js
  packages/scandipwa/src/component/Header/Header.style.scss
  packages/scandipwa/src/component/NavigationAbstract/NavigationAbstract.component.js
  packages/scandipwa/src/component/NewsletterSubscription/NewsletterSubscription.component.js
  packages/scandipwa/src/type/Direction.js
Labels: Status: QA Passed

#3174 #3149 - handle no search results UX
  packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
  packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js
  packages/scandipwa/src/route/CategoryPage/CategoryPage.style.scss
  packages/scandipwa/src/route/SearchPage/SearchPage.container.js
Labels: Status: Failed QA

#3168 #3113 - fix missing props
  packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.js
  packages/scandipwa/src/route/CreateAccount/CreateAccount.container.js
  packages/scandipwa/src/route/ForgotPassword/ForgotPassword.container.js
Labels: Status: Waiting Review, Status: Failed QA

#3172 #3142 - swipe to delete fix no gap
  packages/scandipwa/src/component/CartItem/CartItem.style.scss
  packages/scandipwa/src/component/SwipeToDelete/SwipeToDelete.component.js
  packages/scandipwa/src/component/SwipeToDelete/SwipeToDelete.style.scss
  packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
Labels: Status: Failed QA

#3170 #3147 - fix missing props
  packages/scandipwa/src/component/CategorySort/CategorySort.style.scss
  packages/scandipwa/src/component/Field/Field.container.js
Labels: Status: QA Passed

#3179 #3177 CartPage out of stock bundle fix
  packages/scandipwa/src/component/CartOverlay/CartOverlay.container.js
  packages/scandipwa/src/query/ProductList.query.js
  packages/scandipwa/src/route/CartPage/CartPage.container.js
  packages/scandipwa/src/util/Cart/Cart.js
  packages/scandipwa/src/util/Product/Extract.js
Labels: Status: Failed QA
