Repository scandipwa/scandipwa, pull requests merged in 2022-08, with the labels that each got.

#5094 #5090 - Set swipe background color transparent
  packages/scandipwa/src/component/SwipeToDelete/SwipeToDelete.style.scss
Labels: PR ready for QA

#5096 #3025 - Add support for hideOnDesktop class
  packages/scandipwa/src/component/Menu/Menu.style.scss
  packages/scandipwa/src/component/MenuItem/MenuItem.component.js
Labels: Status: QA Passed

#5095 #3777 - Don`t send not selected subscribition status when sign up
  packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.container.js
Labels: Status: QA Passed

#5092 #3654 - Hide qty for grouped product in wishlist
  packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js
Labels: Status: QA Passed

#5091 4999 Hide vertical scroll bars on wishlist tab when screen is resized
  packages/scandipwa/src/route/MyAccount/MyAccount.style.scss
Labels: Status: QA Passed

#5088 #5032 - Hide tier price if higher than regular price
  packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js
  packages/scandipwa/src/component/ProductPrice/ProductPrice.container.js
  packages/scandipwa/src/type/Price.type.js
Labels: Status: QA Passed

#5086 #4752 - Use correct template for error message on styleguide page
  packages/scandipwa/src/route/StyleGuidePage/StyleGuidePage.component.js
Labels: Status: QA Passed

#5083 #4862 - Render option text as html
  packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js
  packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
Labels: Status: QA Passed

#5080 #4922 - Hide totals if cart is empty
  packages/scandipwa/src/route/CartPage/CartPage.component.js
Labels: Status: QA Passed

#5078 #4928 - Show zero price in my orders table
  packages/scandipwa/src/component/MyAccountOrderTableRow/MyAccountOrderTableRow.component.js
Labels: Status: QA Passed

#5097 See #5072 Added additional check if JWT is expired
  packages/scandipwa/package.json
  packages/scandipwa/src/util/Auth/Token.js
  yarn.lock
Labels: Status: QA Passed, FE

#5121 Virtual Product Customizable Options
  packages/scandipwa/src/query/Cart.query.js
  packages/scandipwa/src/store/Cart/Cart.reducer.js
Labels: Status: QA Passed

#5126 Order Print Page Fix
  packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.component.js
  packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.config.js
  packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.style.scss
Labels: Status: QA Passed

#5103 #5101 - Show cart items quantity on mobile minicart
  packages/scandipwa/src/component/NavigationTabs/NavigationTabs.component.js
Labels: Status: QA Passed

#5129 See #5124 Hid footer navigation on mobile view for the order print page
  packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.style.scss
Labels: Status: QA Passed, FE

#5125 #4826 - Added height to the warning container displayed in the cart for mobile
  packages/scandipwa/src/route/CartPage/CartPage.style.scss
Labels: Status: QA Passed

#5123 updating the payment methods on coupon code change
  packages/scandipwa/src/route/Checkout/Checkout.container.js
Labels: Status: QA Passed

#5117 #4987 - Fixed overlapping downloadable orders table cell content when resized in safari
  packages/scandipwa/src/component/MyAccountMyOrders/MyAccountMyOrders.style.scss
Labels: Status: QA Passed

#5114 #4890 - Change condition for max salable qty is 1
  packages/scandipwa/src/component/FieldNumberWithControls/FieldNumberWithControls.component.js
Labels: Status: QA Passed

#5111 #4908 - Don`t check if forgot pass overlay active on mobile
  packages/scandipwa/src/component/MyAccountForgotPassword/MyAccountForgotPassword.container.js
  packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.container.js
Labels: Status: QA Passed

#5110 #4994 - Fixed overflowing content in checkout address table on mobile
  packages/scandipwa/src/component/CheckoutAddressTable/CheckoutAddressTable.style.scss
Labels: Status: QA Passed

#5109 #4996 - Fix overflowing content in Address book on mobile
  packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.style.scss
Labels: Status: QA Passed

#5107 #5089 - Include product tier price on compare page
  packages/scandipwa/src/component/ProductCompare/ProductCompare.component.js
Labels: Status: QA Passed

#5106 #5041 - Set link for out of stock product in cart
  packages/scandipwa/src/component/CartItem/CartItem.component.js
Labels: Status: QA Passed

#5104 #5098 - Removed character validation for first and last name inputs on registration
  packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.component.js
Labels: Status: QA Passed

#5102 #5099 - Add wrap for category description
  packages/scandipwa/src/component/CategoryDetails/CategoryDetails.style.scss
Labels: Status: QA Passed

#5100 #5040 - Fix infinity loading on cart page after checkout/logout
  packages/scandipwa/src/route/Checkout/Checkout.container.js
  packages/scandipwa/src/store/Cart/Cart.dispatcher.js
  packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
Labels: Status: QA Passed

#5093 #4805 - Use error message from admin panel for shipping
  packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js
  packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.container.js
  packages/scandipwa/src/component/CheckoutDeliveryOptions/CheckoutDeliveryOptions.component.js
Labels: Status: QA Passed

#5079 #4927 - Change style for submit button on checkout
  packages/scandipwa/src/route/Checkout/Checkout.style.scss
Labels: Status: QA Passed

#5067 #4990 - Validate second street address
  packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.container.js
  packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.form.js
Labels: Status: QA Passed

#5059 #4802 - Not render checkbox for free payment
  packages/scandipwa/src/component/CheckoutPayment/CheckoutPayment.component.js
  packages/scandipwa/src/component/CheckoutPayments/CheckoutPayments.config.js
Labels: Status: QA Passed, BE

#5028 QueryDispatcher/Request.js refactor
  packages/scandipwa/src/util/Request/QueryDispatcher.js
  packages/scandipwa/src/util/Request/Request.js
Labels: Status: Failed QA, PR ready for QA
