Repository scandipwa/scandipwa, pull requests merged in 2022-03, with the labels that each got.

#4323 [3446] added isSortSelect property and modified styling to show chevron icon on mobile
  packages/scandipwa/src/component/CategorySort/CategorySort.component.js
  packages/scandipwa/src/component/CategorySort/CategorySort.style.scss
  packages/scandipwa/src/component/Field/Field.component.js
  packages/scandipwa/src/component/Field/Field.container.js
  packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js
  packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js
Labels: Status: QA Passed

#4347 [4055] Added border
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Status: QA Passed

#4346 Issue 4314
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Status: QA Passed

#4348 Modified InCartQuantity to become oval after 99
  packages/scandipwa/src/component/Header/Header.style.scss
Labels: Status: QA Passed

#4150 #4135 My account url's added to routeMap
  packages/scandipwa/src/component/NavigationTabs/NavigationTabs.container.js
Labels: Status: QA Passed

#4366 #4283 added a div selector inside the selector Option with the properties overflow, text-overflow, and white-space
  packages/scandipwa/src/component/CartItem/CartItem.style.scss
Labels: Status: QA Passed

#4370 issue-4235 - Change placeholders count for filters overlay on categories
  packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.config.js
  packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.style.scss
Labels: Status: QA Passed

#4298 issue-3775 - Fetch cms pages on visiting it
  packages/scandipwa/src/component/CmsBlock/CmsBlock.container.js
  packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.container.js
  packages/scandipwa/src/component/Menu/Menu.container.js
  packages/scandipwa/src/component/OfflineNotice/OfflineNotice.container.js
  packages/scandipwa/src/component/SliderWidget/SliderWidget.container.js
  packages/scandipwa/src/component/StoreSwitcher/StoreSwitcher.container.js
  packages/scandipwa/src/route/CmsPage/CmsPage.container.js
  packages/scandipwa/src/route/ContactPage/ContactPage.container.js
  packages/scandipwa/src/route/ProductComparePage/ProductComparePage.container.js
  packages/scandipwa/src/util/Request/DataContainer.js
Labels: High Priority, Status: QA Passed

#4362 Fixed missing line in mobile view under currency
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.style.scss
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Status: QA Passed

#4358 [4327] set loading cart to false when loading guest empty cart
  packages/scandipwa/src/store/Cart/Cart.dispatcher.js
Labels: Status: QA Passed

#4330 #4231 Changed the condition inside the componentDidUpdate method
  packages/scandipwa/src/component/ProductCompare/ProductCompare.container.js
Labels: Status: QA Passed

#4385 fixed bold line under currency and store switcher
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.style.scss
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
  packages/scandipwa/src/component/StoreSwitcher/StoreSwitcher.style.scss
Labels: Status: QA Passed

#4382 [3446] modified ios styling
  packages/scandipwa/src/component/CategorySort/CategorySort.style.scss
Labels: Status: QA Passed

#4384 issue - 4376 - Handle listen for broadcast not for all datacontainers
  packages/scandipwa/src/component/CmsBlock/CmsBlock.container.js
  packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.container.js
  packages/scandipwa/src/component/Menu/Menu.container.js
  packages/scandipwa/src/component/ProductListWidget/ProductListWidget.container.js
  packages/scandipwa/src/component/SliderWidget/SliderWidget.container.js
  packages/scandipwa/src/component/StoreSwitcher/StoreSwitcher.container.js
  packages/scandipwa/src/route/CmsPage/CmsPage.container.js
  packages/scandipwa/src/route/ContactPage/ContactPage.container.js
  packages/scandipwa/src/route/ProductComparePage/ProductComparePage.container.js
  packages/scandipwa/src/util/Request/DataContainer.js
Labels: Status: QA Passed

#4368 Price/Nickname, Quality/Summary and Value/Review are on the same line in a review popup
  packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
Labels: Status: QA Passed

#4386 #4092 - Change symbols in timestamp for IOs
  packages/scandipwa/src/component/MyAccountOrderItemsTable/MyAccountOrderItemsTable.component.js
Labels: Status: QA Passed

#4387 #4371 - Remove breadcrumbs between categories
  packages/scandipwa/src/component/MenuItem/MenuItem.container.js
Labels: Status: QA Passed

#4377 [4338] initialized current address values, set input values to current values
  packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.container.js
  packages/scandipwa/src/component/MyAccountAddressForm/MyAccountAddressForm.form.js
Labels: Status: QA Passed

#4369 Fixed header working as back button in mobile
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/src/component/Popup/Popup.component.js
Labels: Status: QA Passed, Merge Conflicts

#4262 Issue 3900
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/en_US.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.component.js
  packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.container.js
  packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.form.js
  packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.component.js
  packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.container.js
  packages/scandipwa/src/component/MyAccountCustomerForm/MyAccountCustomerForm.component.js
  packages/scandipwa/src/component/MyAccountCustomerForm/MyAccountCustomerForm.container.js
  packages/scandipwa/src/component/MyAccountCustomerForm/MyAccountCustomerForm.form.js
  packages/scandipwa/src/component/MyAccountPasswordForm/MyAccountPasswordForm.component.js
  packages/scandipwa/src/component/MyAccountPasswordForm/MyAccountPasswordForm.form.js
  packages/scandipwa/src/component/PasswordChangeForm/PasswordChangeForm.component.js
  packages/scandipwa/src/component/PasswordChangeForm/PasswordChangeForm.form.js
  packages/scandipwa/src/query/Config.query.js
  packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.component.js
  packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.container.js
  packages/scandipwa/src/util/Validator/Validator.js
Labels: Status: QA Passed, Merge Conflicts

#4372 [3886] modified logic to show locked account error
  packages/scandipwa/src/component/MyAccountInformation/MyAccountInformation.container.js
  packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.container.js
  packages/scandipwa/src/route/LoginAccount/LoginAccount.container.js
  packages/scandipwa/src/route/MyAccount/MyAccount.config.js
  packages/scandipwa/src/route/MyAccount/MyAccount.container.js
Labels: Status: QA Passed

#4429 #4411 - Change indent for product card
  packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
  packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
Labels: Status: QA Passed

#4419 issue-4298 - Dynamically update slider widgets
  packages/scandipwa/src/component/SliderWidget/SliderWidget.container.js
  packages/scandipwa/src/route/CmsPage/CmsPage.container.js
Labels: Status: QA Passed

#4421 #4349 - fixed table data data not breaking into two lines
  packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.style.scss
Labels: Status: QA Passed

#4363 Fixed Price moved from first line to second line
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Status: QA Passed

#4444 Console Errors Fix 5.2.5
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/en_US.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/src/component/AddToCart/AddToCart.container.js
  packages/scandipwa/src/component/CartItem/CartItem.component.js
  packages/scandipwa/src/component/DateSelect/DateSelect.component.js
  packages/scandipwa/src/component/DateSelect/DateSelect.container.js
  packages/scandipwa/src/component/Field/Field.component.js
  packages/scandipwa/src/component/FieldDate/FieldDate.container.js
  packages/scandipwa/src/component/MyAccountForgotPassword/MyAccountForgotPassword.container.js
  packages/scandipwa/src/component/MyAccountNewsletterSubscription/MyAccountNewsletterSubscription.container.js
  packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.container.js
  packages/scandipwa/src/component/Product/Product.component.js
  packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.component.js
  packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.container.js
  packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js
  packages/scandipwa/src/type/Downloadable.type.js
  packages/scandipwa/src/type/Field.type.js
  packages/scandipwa/src/type/ProductList.type.js
Labels: Status: QA Passed

#4441 #4441 - adjusted menu total height
  packages/scandipwa/src/component/Menu/Menu.style.scss
Labels: Status: QA Passed

#4430 Fixed order of customizable option
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.component.js
Labels: Status: QA Passed

#4408 [4247] update navigation state on share wishlist
  packages/scandipwa/src/component/ShareWishlistPopup/ShareWishlistPopup.container.js
Labels: Status: QA Passed

#4407 [3587] modified validation event trigger
  packages/scandipwa/src/component/ProductDownloadableLinks/ProductDownloadableLinks.component.js
Labels: Status: QA Passed

#4391 fixed padding bottom issue in older firefox and older edge
  packages/scandipwa/src/component/Popup/Popup.style.scss
Labels: Status: QA Passed

#4446 [4251] - File's name toLowerCase on validation
  packages/scandipwa/src/component/Field/Field.container.js
Labels: Status: QA Passed

#4398 [4365] set name to lowercase and then capitalize with css
  packages/scandipwa/src/component/Breadcrumb/Breadcrumb.component.js
  packages/scandipwa/src/component/Breadcrumb/Breadcrumb.style.scss
Labels: Status: QA Passed

#4383 Issue 4344
  packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js
  packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Status: QA Passed

#4469 #4434 - added cursor pointer to storeItem-item
  packages/scandipwa/src/component/StoreItem/StoreItem.style.scss
Labels: Status: QA Passed

#4275 [4249] Added sublabel when maxcharacters bigger than 0
  packages/scandipwa/src/component/Field/Field.component.js
  packages/scandipwa/src/component/Field/Field.container.js
  packages/scandipwa/src/component/Product/Product.container.js
  packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js
  packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.style.scss
  packages/scandipwa/src/store/Product/Product.reducer.js
  packages/scandipwa/src/util/Product/Extract.js
  packages/scandipwa/src/util/Validator/Validator.js
Labels: Status: QA Passed

#4468 #4468 - fixed url not parsing = instead of :
  packages/scandipwa/src/util/Url/Url.js
Labels: Status: QA Passed

#4466 #4451 - fixed share whishlist not showing loading state
  packages/scandipwa/src/component/ShareWishlistForm/ShareWishlistForm.component.js
  packages/scandipwa/src/component/ShareWishlistPopup/ShareWishlistPopup.component.js
  packages/scandipwa/src/component/ShareWishlistPopup/ShareWishlistPopup.container.js
Labels: Status: QA Passed

#4465 #4461 Removed unnecessary line
  packages/scandipwa/src/component/Header/Header.style.scss
Labels: Status: QA Passed

#4436 fixed not found page error when redirected from the wishlist page
  packages/scandipwa/src/component/WishlistItem/WishlistItem.container.js
Labels: Status: QA Passed

#4208 [4120] block with widgets width fix
  packages/scandipwa/src/component/ProductListPage/ProductListPage.style.scss
  packages/scandipwa/src/component/ProductListWidget/ProductListWidget.style.scss
  packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
  packages/scandipwa/src/route/CmsPage/CmsPage.style.scss
Labels: Status: QA Passed

#4177 [4072] Margin block fix
  packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
  packages/scandipwa/src/component/ProductPrice/ProductPrice.style.scss
Labels: Status: QA Passed

#4482 5.2.5
  build-packages/create-scandipwa-app/package.json
  build-packages/csa-generator-theme/package.json
  build-packages/eslint-config/package.json
  build-packages/scandipwa-cli/package-lock.json
  build-packages/scandipwa-cli/package.json
  build-packages/scandipwa-development-toolkit-vscode/package-lock.json
  build-packages/scandipwa-development-toolkit-vscode/package.json
  packages/chunk-optimizer/package.json
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/en_US.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/package.json
  packages/scandipwa/src/component/AddToCart/AddToCart.container.js
  packages/scandipwa/src/component/CartItem/CartItem.component.js
  packages/scandipwa/src/component/DateSelect/DateSelect.component.js
  packages/scandipwa/src/component/DateSelect/DateSelect.container.js
  packages/scandipwa/src/component/Field/Field.component.js
  packages/scandipwa/src/component/FieldDate/FieldDate.container.js
  packages/scandipwa/src/component/MyAccountForgotPassword/MyAccountForgotPassword.container.js
  packages/scandipwa/src/component/MyAccountNewsletterSubscription/MyAccountNewsletterSubscription.container.js
  packages/scandipwa/src/component/Product/Product.component.js
  packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
  packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.component.js
  packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.container.js
  packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
  packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js
  packages/scandipwa/src/component/SliderWidget/SliderWidget.container.js
  packages/scandipwa/src/route/CmsPage/CmsPage.container.js
  packages/scandipwa/src/type/Downloadable.type.js
  packages/scandipwa/src/type/Field.type.js
  packages/scandipwa/src/type/ProductList.type.js
  packages/stylelint-config/package.json
Labels: Status: QA Passed

#4414 #4402 - Change create password page with missing token
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.component.js
  packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.container.js
  packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.style.scss
Labels: Status: QA Passed

#4490 #4271 Fixed duplication of the success message
  packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.container.js
Labels: Status: QA Passed

#4485 #4473 - added decode function to header search term
  packages/scandipwa/src/component/Header/Header.component.js
Labels: Status: QA Passed

#4518 Add checks before setting data for customers after log out
  packages/scandipwa/src/route/Checkout/Checkout.container.js
  packages/scandipwa/src/store/Cart/Cart.dispatcher.js
  packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
  packages/scandipwa/src/store/Order/Order.dispatcher.js
  packages/scandipwa/src/store/ProductCompare/ProductCompare.dispatcher.js
  packages/scandipwa/src/store/Wishlist/Wishlist.dispatcher.js
Labels: Status: QA Passed

#4471 [4457] - Increased Checkout-Wrapper padding
  packages/scandipwa/src/route/Checkout/Checkout.style.scss
Labels: Status: QA Passed

#4367 Fixed minimal and maximal value of grouped product
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/src/component/Field/Field.style.scss
  packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.component.js
Labels: Status: QA Passed

#4432 Fixed Filter showing when Page is loading
  packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
  packages/scandipwa/src/route/CategoryPage/CategoryPage.style.scss
Labels: Status: QA Passed

#4074 #4018 Removed discount duplicate and added negative attribute to the discount value
  packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.component.js
  packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.component.js
  packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.component.js
  packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.style.scss
Labels: Status: QA Passed

#4519 #4489 Added styles to component
  packages/scandipwa/src/component/ProductLinks/ProductLinks.style.scss
  packages/scandipwa/src/component/ProductListWidget/ProductListWidget.style.scss
  packages/scandipwa/src/component/RecentlyViewedWidget/RecentlyViewedWidget.style.scss
Labels: Status: QA Passed

#4507 [4463] - Enabled concurrent add/remove from wishlist requests
  packages/scandipwa/src/component/ProductWishlistButton/ProductWishlistButton.container.js
Labels: Status: QA Passed

#4499 #3307 Tax line is displayed in empty cart on a mobile phone
  packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
  packages/scandipwa/src/component/CheckoutOrderSummaryPriceLine/CheckoutOrderSummaryPriceLine.component.js
Labels: Status: QA Passed

#4528 changed prop-type for date to instanceOf(Date)
  packages/scandipwa/src/type/Account.type.js
Labels: PR ready for QA

#4512 Issue 4505
  packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.component.js
  packages/scandipwa/src/component/Field/Field.container.js
  packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.component.js
  packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.container.js
Labels: Status: QA Passed

#4508 #4226 - removed extra bottom border
  packages/scandipwa/src/route/CartPage/CartPage.style.scss
Labels: PR ready for QA

#4339 #4329 Fix for the buttons in 40kSKU
  packages/scandipwa/src/style/cms/block/homepage-category-preview.scss
Labels: Status: QA Passed

#4459 #3965 Fixed dropdown opened
  packages/scandipwa/src/component/FieldSelect/FieldSelect.container.js
Labels: Status: QA Passed

#4456 #4454 - fixed button covering another button on small height devices
  packages/scandipwa/src/component/CheckoutSuccess/CheckoutSuccess.style.scss
Labels: Status: QA Passed

#4509 #4475 added max-height for expanded state of dropdown
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Ready for CR, Status: QA Passed, PR ready for QA

#4539 fixed loading state in overlay sign in form, removed overlay's Loader…
  packages/scandipwa/src/component/MyAccountOverlay/MyAccountOverlay.component.js
  packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.component.js
  packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.container.js
Labels: Status: QA Passed

#4495 [4400] - Radio and Checkbox inputs on resizing - Fixed
  packages/scandipwa/src/component/Field/Field.style.scss
  packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.style.scss
  packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.style.scss
Labels: Status: QA Passed

#4484 #4077 - removed nested form, added scroll logic to inner form
  packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.js
  packages/scandipwa/src/route/Checkout/Checkout.component.js
Labels: Status: QA Passed

#4483 #4455 - removed uppercasing of the user input
  packages/scandipwa/src/route/SearchPage/SearchPage.container.js
  packages/scandipwa/src/route/SearchPage/SearchPage.style.scss
Labels: Status: QA Passed

#4476 [4445] set deafult option if its available
  packages/scandipwa/src/component/ProductBundleOption/ProductBundleOption.container.js
Labels: Status: QA Passed

#4503 #4478 - changed fieldSelect padding
  packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.style.scss
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Status: QA Passed

#4562 Issue 4553 disc prop types
  packages/scandipwa/src/type/Order.type.js
Labels: PR ready for QA

#4300 Search hovering fixed
  packages/scandipwa/src/component/SearchItem/SearchItem.style.scss
  packages/scandipwa/src/component/SearchOverlay/SearchOverlay.style.scss
Labels: Status: QA Passed

#4561 removed propery which replaced loader to the bottom of a card in mywishlist mobile
  packages/scandipwa/src/route/MyAccount/MyAccount.style.scss
Labels: Status: QA Passed

#4547 [3230] - IOS-RTL: Fixed the icon in Add to home screen banner
  packages/scandipwa/src/style/abstract/_icons.scss
Labels: Status: QA Passed

#4546 fixed buttons in cart when resizing
  packages/scandipwa/src/component/CartCoupon/CartCoupon.style.scss
Labels: Status: QA Passed

#4544 Fixed shipping method to stay on same line
  packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.style.scss
Labels: Status: QA Passed

#4494 [4379] - Fixed the offline mode icon in RTL mode
  packages/scandipwa/src/component/OfflineNotice/OfflineNotice.style.scss
Labels: Status: QA Passed

#4462 [4437] - 'Same shipping and billing addresses' checkbox is no longer checked if user has different default billing address
  packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.js
  packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.js
Labels: Status: QA Passed

#4535 #4498 - fixed select on safari mac
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Status: QA Passed

#4491 #3566 Success message can appear a couple of times
  packages/scandipwa/src/component/ProductWishlistButton/ProductWishlistButton.container.js
Labels: Status: QA Passed

#4215 [4138] coupon field missing fix
  packages/scandipwa/src/component/CartCoupon/CartCoupon.style.scss
  packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
  packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.container.js
  packages/scandipwa/src/route/Checkout/Checkout.component.js
Labels: Status: QA Passed

#4572 Fixed Colon after qty moved down on IOS
  packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.style.scss
Labels: Ready for CR, Status: QA Passed

#4443 [2859] - Breadcrumbs on /default issue - Fixed
  packages/scandipwa/src/component/Breadcrumbs/Breadcrumbs.component.js
Labels: Ready for CR, Status: QA Passed

#4467 #4361 - fixed user not be redirected to shipping step when logging in billing
  packages/scandipwa/src/component/Header/Header.container.js
  packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.container.js
  packages/scandipwa/src/route/Checkout/Checkout.config.js
Labels: Ready for CR, Status: QA Passed

#4520 [4375] Missing Product Filter Placeholder Fix
  packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.component.js
  packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.container.js
  packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.component.js
  packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.container.js
  packages/scandipwa/src/component/ProductConfigurableAttributes/ProductConfigurableAttributes.style.scss
  packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
  packages/scandipwa/src/route/CategoryPage/CategoryPage.style.scss
Labels: Ready for CR, Status: QA Passed

#4575 List item text doesn't overlap bullet and number
  packages/scandipwa/src/route/CmsPage/CmsPage.style.scss
Labels: Ready for CR, Status: QA Passed

#4175 [3563] Incorrect message appears in ChangePasswordPage
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/src/component/PasswordChangeForm/PasswordChangeForm.component.js
  packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.component.js
  packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.container.js
Labels: Status: QA Passed

#4559 added flex wrap for order information which caused horizontal scroll
  packages/scandipwa/src/component/MyAccountDashboard/MyAccountDashboard.style.scss
  packages/scandipwa/src/component/MyAccountOrderInformation/MyAccountOrderInformation.style.scss
Labels: Status: QA Passed

#4581 [3146] - Aligned Compare's close-buttons with their product's title
  packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.style.scss
Labels: Status: QA Passed

#4599 #4594 Long word in table on CMS page is not moved to second line
  packages/scandipwa/src/route/CmsPage/CmsPage.style.scss
Labels: Status: QA Passed

#4616 Added wishlist check
  packages/scandipwa/src/component/Header/Header.component.js
  packages/scandipwa/src/component/Header/Header.container.js
Labels: Status: QA Passed

#4603 Bound the hideNotification method triggered by onClick
  packages/scandipwa/src/component/Notification/Notification.component.js
Labels: Status: QA Passed

#4571 added check for attributes if they have attribute_values
  packages/scandipwa/src/component/ProductCard/ProductCard.component.js
Labels: Status: QA Passed

#4600 Fixed product name not aligned with cross on IOS
  packages/scandipwa/src/component/WishlistItem/WishlistItem.component.js
  packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
Labels: Status: QA Passed

#4582 #4035 Minus and plus button disabled if product only 1 in stock
  packages/scandipwa/src/component/FieldNumber/FieldNumber.component.js
Labels: Status: QA Passed

#4576 Fixes Never-Ending loader if user canceled second file input
  packages/scandipwa/src/component/FieldFile/FieldFile.container.js
Labels: Status: QA Passed

#4565 Fixed mobile hover state
  packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.style.scss
  packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
  packages/scandipwa/src/component/ProductAlerts/ProductAlerts.style.scss
  packages/scandipwa/src/style/abstract/_button.scss
  packages/scandipwa/src/style/abstract/_icons.scss
  packages/scandipwa/src/style/abstract/_media.scss
  packages/scandipwa/src/style/base/_input.scss
  packages/scandipwa/src/style/base/_link.scss
Labels: Status: QA Passed

#4555 [4364] - Background is no longer visible in dropdown lists
  packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Status: QA Passed

#4431 [4273] - Footer jumping on HomepageCategoriesButtons clicking - Fixed
  packages/scandipwa/src/component/Html/Html.component.js
  packages/scandipwa/src/component/Router/Router.component.js
  packages/scandipwa/src/component/Router/Router.style.scss
Labels: Status: QA Passed

#4412 Fixed Excl. tax location so it won't overflow
  packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.component.js
  packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.style.scss
Labels: Status: QA Passed

#4615 #4556 Loaderis absent on PLP after refresh of page
  packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
Labels: Status: QA Passed

#4289 Issue 3751 - Add Print Order functionality
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/src/component/FieldSelect/FieldSelect.component.js
  packages/scandipwa/src/component/Footer/Footer.component.js
  packages/scandipwa/src/component/Image/Image.component.js
  packages/scandipwa/src/component/Image/Image.container.js
  packages/scandipwa/src/component/Link/Link.component.js
  packages/scandipwa/src/component/Logo/Logo.component.js
  packages/scandipwa/src/component/Meta/Meta.component.js
  packages/scandipwa/src/component/Meta/Meta.container.js
  packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.component.js
  packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.config.js
  packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.container.js
  packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.style.scss
  packages/scandipwa/src/component/MyAccountOrderItemsTable/MyAccountOrderItemsTable.component.js
  packages/scandipwa/src/component/MyAccountOrderItemsTable/MyAccountOrderItemsTable.container.js
  packages/scandipwa/src/component/MyAccountOrderItemsTable/MyAccountOrderItemsTable.style.scss
  packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.component.js
  packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.container.js
  packages/scandipwa/src/component/MyAccountOrderItemsTableRow/MyAccountOrderItemsTableRow.style.scss
  packages/scandipwa/src/component/MyAccountOrderPrint/MyAccountOrderPrint.component.js
  packages/scandipwa/src/component/MyAccountOrderPrint/MyAccountOrderPrint.config.js
  packages/scandipwa/src/component/MyAccountOrderPrint/MyAccountOrderPrint.container.js
  packages/scandipwa/src/component/MyAccountOrderPrint/MyAccountOrderPrint.style.scss
  packages/scandipwa/src/component/MyAccountOrderPrint/index.js
  packages/scandipwa/src/component/MyAccountOrderTabs/MyAccountOrderTabs.style.scss
  packages/scandipwa/src/component/MyAccountOrderTotals/MyAccountOrderTotals.style.scss
  packages/scandipwa/src/component/Router/Router.component.js
  packages/scandipwa/src/component/Router/Router.config.js
  packages/scandipwa/src/component/Router/Router.container.js
  packages/scandipwa/src/query/Order.query.js
  packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.component.js
  packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.container.js
  packages/scandipwa/src/route/OrderPrintPage/OrderPrintPage.style.scss
  packages/scandipwa/src/route/OrderPrintPage/index.js
  packages/scandipwa/src/store/Order/Order.dispatcher.js
  packages/scandipwa/src/style/abstract/_media.scss
  packages/scandipwa/src/style/base/_reset.scss
  packages/scandipwa/src/style/base/_table.scss
  packages/scandipwa/src/type/Order.type.js
  packages/scandipwa/src/util/Mobile/isMobile.js
Labels: Status: QA Passed

#4620 [4596] - IsRequired stars are no longer away from options titles
  packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.style.scss
  packages/scandipwa/src/component/ProductCustomizableOptions/ProductCustomizableOptions.style.scss
Labels: Status: QA Passed

#4580 #4530 List/Grid icons and Sort by dropdown is shifted left on PLP
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
  packages/scandipwa/src/route/CategoryPage/CategoryPage.component.js
  packages/scandipwa/src/route/CategoryPage/CategoryPage.style.scss
Labels: Status: QA Passed

#4566 Fixed product description not shown if only image
  packages/scandipwa/src/component/ProductInformation/ProductInformation.component.js
  packages/scandipwa/src/route/ProductPage/ProductPage.container.js
Labels: Status: QA Passed

#4574 [4000] - Empty Cart on Reorder
  packages/scandipwa/src/route/CartPage/CartPage.component.js
  packages/scandipwa/src/route/CartPage/CartPage.container.js
  packages/scandipwa/src/route/CartPage/CartPage.style.scss
  packages/scandipwa/src/store/Cart/Cart.dispatcher.js
Labels: Status: QA Passed

#4568 #4557 - fixed select display error on mobile
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Status: QA Passed
