Repository scandipwa/scandipwa, pull requests merged in 2022-06, with the labels that each got.

#4816 #4800 - added region, country and postal code in address.
  packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.component.js
  packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.container.js
  packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.table.js
  packages/scandipwa/src/component/MyAccountDashboard/MyAccountDashboard.component.js
  packages/scandipwa/src/component/MyAccountOrderInformation/MyAccountOrderInformation.component.js
Labels: Status: QA Passed

#4873 4730 - removed red outline on deleting coupon
  packages/scandipwa/src/component/CartCoupon/CartCoupon.component.js
Labels: Status: QA Passed

#4889 #4753 added line after currency in mobile
  packages/scandipwa/src/component/FieldSelect/FieldSelect.style.scss
Labels: Status: QA Passed

#4828 #4812 adjusted form width when ratings are disabled
  packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.component.js
  packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
Labels: Status: QA Passed

#4810 #4803 - added order total and subtotal fields to orders equal to 0
  packages/scandipwa/src/component/CartItem/CartItem.component.js
  packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js
  packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
  packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss
  packages/scandipwa/src/component/CheckoutOrderSummaryPriceLine/CheckoutOrderSummaryPriceLine.component.js
Labels: Status: QA Passed

#4885 #4786 - corrected loader on RTL
  packages/scandipwa/src/route/CartPage/CartPage.style.scss
Labels: PR ready for QA

#4794 fixed line height for textareas from other places
  packages/scandipwa/src/component/Field/Field.style.scss
  packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
Labels: Status: QA Passed

#4809 [4798] - error on clicking Add to Cart while the product is loading
  packages/scandipwa/src/component/ProductCard/ProductCard.component.js
  packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
Labels: Status: QA Passed

#4849 #4340 - Remove meta update when category is not yet received
  packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js
Labels: Status: QA Passed

#4877 [4863] Corrected the new address notification message.
  packages/scandipwa/src/component/MyAccountAddressPopup/MyAccountAddressPopup.container.js
Labels: Status: QA Passed

#4841 Created customer_id field and pass to BE to get its email
  packages/scandipwa/composer.json
  packages/scandipwa/i18n/da_DK.json
  packages/scandipwa/i18n/de_DE.json
  packages/scandipwa/i18n/es_ES.json
  packages/scandipwa/i18n/fa_IR.json
  packages/scandipwa/i18n/fi_FI.json
  packages/scandipwa/i18n/fr_FR.json
  packages/scandipwa/i18n/it_IT.json
  packages/scandipwa/i18n/lv_LV.json
  packages/scandipwa/i18n/nb_NO.json
  packages/scandipwa/i18n/nl_NL.json
  packages/scandipwa/i18n/pl_PL.json
  packages/scandipwa/i18n/pt_BR.json
  packages/scandipwa/i18n/ru_RU.json
  packages/scandipwa/i18n/sl_SI.json
  packages/scandipwa/i18n/sv_SE.json
  packages/scandipwa/i18n/tr_TR.json
  packages/scandipwa/i18n/zh_TW.json
  packages/scandipwa/package.json
  packages/scandipwa/src/query/MyAccount.query.js
  packages/scandipwa/src/route/Checkout/Checkout.container.js
  packages/scandipwa/src/route/PasswordChangePage/PasswordChangePage.container.js
  packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
Labels: BE, PR ready for QA

#4901 #4800- corrected issue with state appearing as null
  packages/scandipwa/src/component/MyAccountAddressTable/MyAccountAddressTable.table.js
Labels: Status: QA Passed

#4866 CTO2-545 - Image on PDP changes in size when opening
  packages/scandipwa/src/component/CarouselScroll/CarouselScroll.style.scss
  packages/scandipwa/src/component/CarouselScrollItem/CarouselScrollItem.style.scss
  packages/scandipwa/src/component/ProductGallery/ProductGallery.style.scss
Labels: Status: QA Passed

#4806 [4660] - double Order Summary loader on singn-in on checkout - fixed
  packages/scandipwa/src/route/Checkout/Checkout.component.js
  packages/scandipwa/src/store/Cart/Cart.dispatcher.js
Labels: Status: QA Passed

#4895 #4850 change error to the 404 page
  packages/scandipwa/src/route/MyAccount/MyAccount.component.js
  packages/scandipwa/src/route/MyAccount/MyAccount.container.js
Labels: Status: QA Passed

#4815 Added required prop(value) to Field type numberWithControls in Groupe…
  packages/scandipwa/src/component/GroupedProductsItem/GroupedProductsItem.component.js
Labels: Status: QA Passed

#4935 Making the popup flex so the child can shrink
  packages/scandipwa/src/component/StoreInPickUpPopup/StoreInPickUpPopup.style.scss
Labels: Status: QA Passed

#4930 fixed the data parsing
  packages/scandipwa/src/util/Product/Transform.js
Labels: Status: QA Passed

#4882 [4820] added padding top to subtotal on mobile
  packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.style.scss
Labels: Status: QA Passed

#4867 Updating the state of productActions component on fieldReset
  packages/scandipwa/src/component/AddToCart/AddToCart.container.js
  packages/scandipwa/src/component/Field/Field.container.js
  packages/scandipwa/src/component/Product/Product.component.js
  packages/scandipwa/src/component/Product/Product.container.js
  packages/scandipwa/src/component/ProductCustomizableOption/ProductCustomizableOption.component.js
Labels: Status: QA Passed

#4937 padding same as search query
  packages/scandipwa/src/component/SearchOverlay/SearchOverlay.component.js
  packages/scandipwa/src/component/SearchOverlay/SearchOverlay.style.scss
Labels: Status: QA Passed

#4888 #4688 - Close store in popup on mobile after store change
  packages/scandipwa/src/component/StoreInPickUpPopup/StoreInPickUpPopup.container.js
Labels: Status: QA Passed

#4886 #3768 - Create handler for chunk load error in offline mode
  packages/scandipwa/src/component/ErrorHandler/ErrorHandler.component.js
  packages/scandipwa/src/component/ErrorHandler/index.js
  packages/scandipwa/src/component/Router/Router.component.js
  packages/scandipwa/src/component/Router/Router.container.js
Labels: Status: QA Passed

#4953 #4952 Wrong Qty of steps on Checkout
  packages/scandipwa/src/route/Checkout/Checkout.component.js
Labels: Status: QA Passed

#4947 [4660] - login fields don't disappear on checkout after sign-in from header - fixed
  packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.component.js
  packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.component.js
Labels: Status: QA Passed

#4939 fix yt videos with hyphens, set base image position to a valid one
  packages/scandipwa/src/component/ProductGallery/ProductGallery.container.js
  packages/scandipwa/src/component/VideoPopup/VideoPopup.config.js
Labels: Status: QA Passed

#4965 fixed styles for FF and Safari
  packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.style.scss
Labels: Status: QA Passed

#4968 4786 loader not centered
  packages/scandipwa/src/route/CartPage/CartPage.style.scss
Labels: Status: QA Passed

#4946 #4899 Stop scrollbar and scroller block from overriding each-others' `scrollLeft`
  packages/scandipwa/src/component/ProductCompare/ProductCompare.component.js
  packages/scandipwa/src/component/ProductCompare/ProductCompare.container.js
Labels: Status: QA Passed

#4969 error caused because default func type is null
  packages/scandipwa/src/component/AddToCart/AddToCart.component.js
  packages/scandipwa/src/component/AddToCart/AddToCart.container.js
  packages/scandipwa/src/component/ProductCompareItem/ProductCompareItem.component.js
Labels: Status: QA Passed

#4907 #4747 hid price while the product was loading or out of stock
  packages/scandipwa/src/component/Product/Product.component.js
  packages/scandipwa/src/component/ProductPrice/ProductPrice.component.js
  packages/scandipwa/src/component/ProductPrice/ProductPrice.container.js
Labels: Status: QA Passed

#4977 #4330 - Update meta if category didn`t changed after CMS
  packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js
Labels: Status: QA Passed
