Repository scandipwa/scandipwa, pull requests merged in 2022-07, with the labels that each got.

#4995 [4932] - page with address can be resized on Android - fixed
  packages/scandipwa/public/index.html
Labels: Status: QA Passed

#4959 #4957 Edited `requiresConfiguration()` to check grouped items for options too
  packages/scandipwa/src/component/ProductCard/ProductCard.component.js
Labels: Status: QA Passed

#4951 2948 nav tab blink
  packages/scandipwa/src/component/Router/Router.component.js
Labels: Status: QA Passed

#4918 [543] removed the animation for filter overlay
  packages/scandipwa/src/component/CategoryFilterOverlay/CategoryFilterOverlay.style.scss
Labels: Status: QA Passed

#4874 [544] removed notification fade in, fade out, and field shake animations
  packages/scandipwa/src/component/Notification/Notification.style.scss
  packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
Labels: Status: QA Passed

#4848 [4825] - cart delete item button misaligned - fixed
  packages/scandipwa/.vscode/launch.json
  packages/scandipwa/src/component/CartItem/CartItem.style.scss
Labels: Status: QA Passed

#4900 #4734 corrected issue with cursor on attributes
  packages/scandipwa/src/component/ProductAttributeValue/ProductAttributeValue.style.scss
Labels: Status: QA Passed

#4792 issue-4779 - Form validation at checkout step
  packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.component.js
  packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.js
  packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.component.js
  packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.container.js
  packages/scandipwa/src/component/CheckoutGuestForm/CheckoutGuestForm.style.scss
  packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.component.js
  packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.container.js
  packages/scandipwa/src/component/MyAccountSignIn/MyAccountSignIn.component.js
  packages/scandipwa/src/route/Checkout/Checkout.component.js
  packages/scandipwa/src/route/Checkout/Checkout.container.js
Labels: Status: QA Passed

#4993 [4931] - Select Files button missing hover effect - fixed
  packages/scandipwa/src/component/Field/Field.style.scss
  packages/scandipwa/src/component/FieldFile/FieldFile.component.js
  packages/scandipwa/src/route/UrlRewrites/UrlRewrites.container.js
Labels: Status: QA Passed

#5007 Missing Subtotal Fix
  packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
Labels: Status: QA Passed

#4979 4949 - jumping loaders - fixed
  packages/scandipwa/src/component/Router/Router.component.js
  packages/scandipwa/src/component/Router/Router.style.scss
Labels: Status: QA Passed

#4961 #809 - Get cart when switch currency
  packages/scandipwa/src/query/Config.query.js
Labels: PR ready for QA

#5012 Master oops page hotfix
  packages/scandipwa/src/component/Router/Router.component.js
Labels: Status: QA Passed

#4984 [4974] - 'My billing and shipping are the same' isn't selected - fixed
  packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.component.js
  packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.js
  packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
Labels: Status: QA Passed

#5002 #2454 - added a check for whether reviews are enabled
  packages/scandipwa/src/component/ProductTabs/ProductTabs.component.js
  packages/scandipwa/src/route/ProductPage/ProductPage.component.js
  packages/scandipwa/src/route/ProductPage/ProductPage.container.js
Labels: Status: QA Passed

#4997 [3731] - wrong content on quick route changes w/ slow internet - fixed
  packages/scandipwa/src/util/Request/QueryDispatcher.js
  packages/scandipwa/src/util/Request/Request.js
Labels: Status: QA Passed

#4943 #4277 Save multiple `quoteId` tokens in localstorage with `{website_code: quote_id}` pairs
  packages/m2-theme/public/index.php
  packages/scandipwa/public/index.html
  packages/scandipwa/src/store/Cart/Cart.dispatcher.js
  packages/scandipwa/src/util/Cart/Token.js
Labels: BE, FE, PR ready for QA

#5019 let the label shrink
  packages/scandipwa/src/component/Field/Field.style.scss
Labels: Status: QA Passed

#5018 message should be turned into string
  packages/scandipwa/src/component/MyAccountForgotPassword/MyAccountForgotPassword.container.js
Labels: Status: QA Passed

#5023 #5000 - Display cross sell product in cart
  packages/scandipwa/src/route/CartPage/CartPage.component.js
  packages/scandipwa/src/route/CartPage/CartPage.container.js
  packages/scandipwa/src/store/LinkedProducts/LinkedProducts.dispatcher.js
Labels: Status: QA Passed

#5025 #5020 - Centrilize plus/minus button for bundle products
  packages/scandipwa/src/component/ProductBundleOptions/ProductBundleOptions.style.scss
Labels: Status: QA Passed

#5037 #3006 - Made cart active on checkout steps
  packages/scandipwa/src/component/NavigationTabs/NavigationTabs.component.js
Labels: Status: QA Passed

#5030 #4325 - Change gaps for review popup
  packages/scandipwa/src/component/ProductReviewForm/ProductReviewForm.style.scss
Labels: Status: QA Passed

#5026 #4985 - Add placeholder for price on PLP
  packages/scandipwa/src/component/ProductActions/ProductActions.component.js
  packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
Labels: Status: QA Passed

#4843 #2685 - Add orderID to customer data on registration after checkout
  packages/scandipwa/src/component/CheckoutSuccess/CheckoutSuccess.component.js
  packages/scandipwa/src/component/MyAccountCreateAccount/MyAccountCreateAccount.container.js
  packages/scandipwa/src/component/MyAccountOrder/MyAccountOrder.config.js
  packages/scandipwa/src/query/MyAccount.query.js
  packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
Labels: Status: QA Passed, BE

#5035 #3012 - Set header for my account page
  packages/scandipwa/src/component/Header/Header.container.js
  packages/scandipwa/src/route/MyAccount/MyAccount.container.js
Labels: Status: QA Passed

#5048 #4690 - Field stay green after submit if not required
  packages/scandipwa/src/component/Field/Field.style.scss
Labels: Status: QA Passed

#5047 let the label shrink for customizable items
  packages/scandipwa/src/component/Field/Field.style.scss
Labels: Status: QA Passed

#4948 remove-padding
  packages/scandipwa/src/component/SearchOverlay/SearchOverlay.component.js
  packages/scandipwa/src/component/SearchOverlay/SearchOverlay.style.scss
Labels: Status: QA Passed

#5052 #4883 - Add wrap for options in wishlist
  packages/scandipwa/src/component/WishlistItem/WishlistItem.style.scss
Labels: Status: QA Passed

#5051 #4755 - Fix x scroll on firefox
  packages/scandipwa/src/component/CurrencySwitcher/CurrencySwitcher.style.scss
Labels: Status: QA Passed

#5049 passing base src if large is absent
  packages/scandipwa/src/component/ProductGallery/ProductGallery.component.js
Labels: Status: QA Passed

#5031 [4986] Include discount property in wishlist item's data
  packages/scandipwa/src/store/Wishlist/Wishlist.dispatcher.js
  packages/scandipwa/src/util/Wishlist/Wishlist.js
Labels: Status: QA Passed

#5082 #4881 - Change default plp type value
  packages/scandipwa/src/route/CategoryPage/CategoryPage.container.js
Labels: Status: QA Passed

#5081 #4923 - Made the same indent for product placeholder on widget
  packages/scandipwa/src/component/ProductCard/ProductCard.style.scss
Labels: Status: QA Passed

#5075 #5005 - Add wrap for short name
  packages/scandipwa/src/component/ProductActions/ProductActions.style.scss
  packages/scandipwa/src/component/ProductInformation/ProductInformation.style.scss
Labels: Status: QA Passed

#5074 #5050 - Validate message field in share wishlist form
  packages/scandipwa/src/component/ShareWishlistForm/ShareWishlistForm.form.js
Labels: Status: QA Passed

#5073 #5060 - Select none for not required bundle radio option
  packages/scandipwa/src/component/ProductBundleOption/ProductBundleOption.component.js
  packages/scandipwa/src/util/Product/Transform.js
Labels: Status: QA Passed

#5071 #5046 - Not set subscribe status if customer is empty
  packages/scandipwa/src/component/MyAccountNewsletterSubscription/MyAccountNewsletterSubscription.container.js
Labels: Status: QA Passed

#5068 #1656 - Set table height on my account
  packages/scandipwa/src/component/MyAccountMyOrders/MyAccountMyOrders.style.scss
Labels: Status: QA Passed

#5021 #3701 - Getting cart using default magento functions
  packages/scandipwa/src/component/CartItem/CartItem.component.js
  packages/scandipwa/src/component/CartItem/CartItem.container.js
  packages/scandipwa/src/component/CartOverlay/CartOverlay.component.js
  packages/scandipwa/src/component/CartOverlay/CartOverlay.container.js
  packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.component.js
  packages/scandipwa/src/component/CheckoutBilling/CheckoutBilling.container.js
  packages/scandipwa/src/component/CheckoutDeliveryOption/CheckoutDeliveryOption.container.js
  packages/scandipwa/src/component/CheckoutOrderSummary/CheckoutOrderSummary.component.js
  packages/scandipwa/src/component/CheckoutOrderSummaryPriceLine/CheckoutOrderSummaryPriceLine.component.js
  packages/scandipwa/src/component/CheckoutShipping/CheckoutShipping.component.js
  packages/scandipwa/src/component/Header/Header.component.js
  packages/scandipwa/src/component/Klarna/Klarna.component.js
  packages/scandipwa/src/component/NavigationTabs/NavigationTabs.component.js
  packages/scandipwa/src/query/Cart.query.js
  packages/scandipwa/src/query/Checkout.query.js
  packages/scandipwa/src/query/Config.query.js
  packages/scandipwa/src/query/Wishlist.query.js
  packages/scandipwa/src/route/CartPage/CartPage.component.js
  packages/scandipwa/src/route/CartPage/CartPage.container.js
  packages/scandipwa/src/route/Checkout/Checkout.component.js
  packages/scandipwa/src/route/Checkout/Checkout.container.js
  packages/scandipwa/src/store/Cart/Cart.dispatcher.js
  packages/scandipwa/src/store/Cart/Cart.reducer.js
  packages/scandipwa/src/store/MyAccount/MyAccount.dispatcher.js
  packages/scandipwa/src/util/Auth/Token.js
  packages/scandipwa/src/util/Cart/Cart.js
  packages/scandipwa/src/util/Cart/Token.js
Labels: Status: QA Passed, BE
